export const COMMON_HEADER_NAMES: string[] = [
  "Accept",
  "Accept-Encoding",
  "Accept-Language",
  "Authorization",
  "Cache-Control",
  "Connection",
  "Content-Length",
  "Content-Type",
  "Cookie",
  "Host",
  "If-Modified-Since",
  "If-None-Match",
  "Origin",
  "Pragma",
  "Range",
  "Referer",
  "User-Agent",
  "X-Api-Key",
  "X-Csrf-Token",
  "X-Forwarded-For",
  "X-Request-Id",
  "X-Requested-With",
];

export const COMMON_CONTENT_TYPES: string[] = [
  "application/json",
  "application/x-www-form-urlencoded",
  "multipart/form-data",
  "text/plain",
  "text/html",
  "application/xml",
  "application/octet-stream",
];
